# SPDX-License-Identifier: AGPL-3.0-or-later
"""Regenerate .claude/skills from the maintained Codex skills in .agents/skills.

Upstream only maintains the Codex copies. This script mirrors them into
.claude/skills with Codex-runtime wording translated to Claude Code, so the
Claude driver follows the same current contracts. Re-run after pulling
upstream changes:

    .venv/bin/python scripts/sync_claude_skills.py

Edit the .agents source (or the rewrite table below), not the generated copy.
"""
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / ".agents" / "skills"
DEST = ROOT / ".claude" / "skills"

# Author-only tooling and the Codex-native scheduler (it launches `codex`
# sessions via src.codex_runner) have no Claude Code equivalent.
EXCLUDED = {"cc-sync-runner", "cc-sync-execute-loop", "daily-work-tweet", "canvas-cron"}
# Codex UI metadata, not skill content.
SKIPPED_FILES = {"agents/openai.yaml"}

GENERATED_MARKER = "<!-- generated by scripts/sync_claude_skills.py -->"

PREAMBLE = f"""{GENERATED_MARKER}
> **Claude Code copy.** Generated from `.agents/skills/{{name}}/SKILL.md`; edit
> the source and re-run `scripts/sync_claude_skills.py` instead of editing here.
> A "Claude Code subagent" is one launched with the Agent tool; a "skill
> handoff" invokes the named skill with the Skill tool. The session identifier
> is `CLAUDE_CODE_SESSION_ID`, resolved by
> `src.authorization.current_authorization_session()`. Run Python as
> `.venv/bin/python` if bare `python` is not on PATH.
"""

# Ordered: specific passages first, then generic wording.
REWRITES: list[tuple[str, str]] = [
    (
        r"Keep `\.claude/` read-only\. It may be inspected as frozen behavioral history"
        r"[^`]*?Do not write `\.claude`\.",
        "Write the tracked skill under `.claude/skills/` (the Claude Code driver's\n"
        "skill directory). No content from private legacy playbooks may be copied\n"
        "into the public skill.",
    ),
    (
        r"These are Codex native subagent handoffs, not Claude `Agent\(\.\.\.\)` calls and not\s+"
        r"shell-launched model sessions\.",
        "These are Claude Code subagents launched with the Agent tool, not\n"
        "shell-launched model sessions.",
    ),
    (
        r"In current Codex this is\s+normally `CODEX_THREAD_ID`; the helper supports `CODEX_SESSION_ID` only as a\s+"
        r"runtime compatibility fallback\. Do not read Claude variables, invent a UUID,",
        "Under Claude Code this is\n`CLAUDE_CODE_SESSION_ID`. Do not invent a UUID,",
    ),
    (r"do not shell-launch a model, use a Claude-specific tool, or copy",
     "do not shell-launch a model or copy"),
    (r'"owner_kind": "codex"', '"owner_kind": "claude"'),
    (r"STOP if you are Codex reading this", "STOP if you are the agent reading this"),
    (r"current(\s+)Codex(\s+)thread/session", r"current\1Claude Code\2session"),
    (r"native(\s+)Codex", r"Claude\1Code"),
    (r"Codex(\s+)native", r"Claude\1Code"),
    (r"`\.agents/skills/", "`.claude/skills/"),
    (r"\bCodex\b", "Claude Code"),
]


def translate(text: str, name: str) -> str:
    for pattern, replacement in REWRITES:
        text = re.sub(pattern, replacement, text, flags=re.DOTALL)
    match = re.match(r"(---\n.*?\n---\n)", text, flags=re.DOTALL)
    if not match:
        raise SystemExit(f"{name}: SKILL.md has no frontmatter")
    head = match.group(1)
    return head + "\n" + PREAMBLE.format(name=name) + text[len(head):]


def sync() -> list[str]:
    synced: list[str] = []
    for src_dir in sorted(p for p in SOURCE.iterdir() if p.is_dir()):
        name = src_dir.name
        if name in EXCLUDED:
            continue
        dest_dir = DEST / name
        if dest_dir.exists():
            shutil.rmtree(dest_dir)
        for src_file in sorted(p for p in src_dir.rglob("*") if p.is_file()):
            rel = src_file.relative_to(src_dir).as_posix()
            if rel in SKIPPED_FILES:
                continue
            out = dest_dir / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            if rel == "SKILL.md":
                out.write_text(
                    translate(src_file.read_text(encoding="utf-8"), name),
                    encoding="utf-8",
                )
            else:
                shutil.copy2(src_file, out)
        synced.append(name)
    return synced


if __name__ == "__main__":
    names = sync()
    print(f"synced {len(names)} skills into {DEST.relative_to(ROOT)}: {', '.join(names)}")
    sys.exit(0)
